[tool.poetry]
name = "prefect-sample"
version = "0.1.0"
description = ""
authors = ["Yasunori Horikoshi <hotoku@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
<<<<<<< HEAD
prefect = {extras = ["gcp"], version = "^0.15.3"}
=======
prefect = "^0.15.1"
mypy = "^0.910"
>>>>>>> 650e1a4 (sample)

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
